[[CURRENCIES]]
code="xusheng2"
issuer="GDXVEJXFI6AXJPFWJSIVCX67PLYC622YBR4ECH7ROBUCMIHV2FLZADCS"
name="Xusheng Test Token"
desc="This is a test token created by Wang Xusheng on Pi Testnet. Total supply: 100,000,000."
image="https://raw.githubusercontent.com/xusheng2/wangxusheng.github.io/main/xusheng.png"

